### ISSUE TITLE
Building container causes error on zeppelin web application

### ISSUE THREAD

**Issue by jramapuram** [dylanmei/docker-zeppelin#10]
```bash
[INFO] Zeppelin: Server ................................... SKIPPED
[INFO] Zeppelin: Packaging distribution ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:25 min
[INFO] Finished at: 2016-06-14T19:17:26+00:00
[INFO] Final Memory: 113M/688M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25:grunt (grunt build) on project zeppelin-web: Failed to run task: 'grunt build --no-color' failed. (error code 137) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :zeppelin-web
The command '/bin/sh -c set -ex  && buildDeps='     git     bzip2  '  && apt-get update && apt-get install -y --no-install-recommends $buildDeps  && curl -sL http://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz    | gunzip    | tar x -C /tmp/  && git clone https://github.com/apache/zeppelin.git /usr/src/zeppelin  && cd /usr/src/zeppelin  && git checkout -q $ZEPPELIN_COMMIT  && sed -i 's/--no-color/buildSkipTests --no-color/' zeppelin-web/pom.xml  && MAVEN_OPTS="-Xms512m -Xmx1024m" /tmp/apache-maven-3.3.9/bin/mvn --batch-mode package -DskipTests -Pbuild-distr   -pl 'zeppelin-interpreter,zeppelin-zengine,zeppelin-display,spark-dependencies,spark,markdown,angular,shell,hbase,postgresql,jdbc,elasticsearch,zeppelin-web,zeppelin-server,zeppelin-distribution'  && tar xvf /usr/src/zeppelin/zeppelin-distribution/target/zeppelin*.tar.gz -C /usr/  && mv /usr/zeppelin* $ZEPPELIN_HOME  && mkdir -p $ZEPPELIN_HOME/logs  && mkdir -p $ZEPPELIN_HOME/run  && rm -rf $ZEPPELIN_NOTEBOOK_DIR/r  && apt-get purge -y --auto-remove $buildDeps  && rm -rf /var/lib/apt/lists/*  && rm -rf /usr/src/zeppelin  && rm -rf /root/.m2  && rm -rf /root/.npm  && rm -rf /tmp/*' returned a non-zero code: 1
```

In detail with `-e` attached:
```bash
[INFO] Zeppelin: web Application .......................... FAILURE [03:28 min]
[INFO] Zeppelin: Server ................................... SKIPPED
[INFO] Zeppelin: Packaging distribution ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:53 min
[INFO] Finished at: 2016-06-14T20:17:29+00:00
[INFO] Final Memory: 112M/691M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25:grunt (grunt build) on project zeppelin-web: Failed to run task: 'grunt build --no-color' failed. (error code 137) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25:grunt (grunt build) on project zeppelin-web: Failed to run task
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:66)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'grunt build --no-color' failed. (error code 137)
        at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:59)
        at com.github.eirslett.maven.plugins.frontend.mojo.GruntMojo.execute(GruntMojo.java:64)
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:64)
        ... 22 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :zeppelin-web
The command '/bin/sh -c set -ex  && buildDeps='     git     bzip2  '  && apt-get update && apt-get install -y --no-install-recommends $buildDeps  && curl -sL http://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz    | gunzip    | tar x -C /tmp/  && git clone https://github.com/apache/zeppelin.git /usr/src/zeppelin  && cd /usr/src/zeppelin  && git checkout -q $ZEPPELIN_COMMIT  && sed -i 's/--no-color/buildSkipTests --no-color/' zeppelin-web/pom.xml  && MAVEN_OPTS="-Xms512m -Xmx1024m" /tmp/apache-maven-3.3.9/bin/mvn -e --batch-mode package -DskipTests -Pbuild-distr   -pl 'zeppelin-interpreter,zeppelin-zengine,zeppelin-display,spark-dependencies,spark,markdown,angular,shell,hbase,postgresql,jdbc,elasticsearch,zeppelin-web,zeppelin-server,zeppelin-distribution'  && tar xvf /usr/src/zeppelin/zeppelin-distribution/target/zeppelin*.tar.gz -C /usr/  && mv /usr/zeppelin* $ZEPPELIN_HOME  && mkdir -p $ZEPPELIN_HOME/logs  && mkdir -p $ZEPPELIN_HOME/run  && rm -rf $ZEPPELIN_NOTEBOOK_DIR/r  && apt-get purge -y --auto-remove $buildDeps  && rm -rf /var/lib/apt/lists/*  && rm -rf /usr/src/zeppelin  && rm -rf /root/.m2  && rm -rf /root/.npm  && rm -rf /tmp/*' returned a non-zero code: 1
```

**Comment by dylanmei** [comment]
There's a line in the `Dockerfile` for disabling some NodeJS tests that don't run gracefully during the Docker build. Ensure this line exists in your setup: https://github.com/dylanmei/docker-zeppelin/blob/master/Dockerfile#L44

If you're still having trouble, I'd like to know more about how your setup is different than mine (which Zeppelin commit, which OS, etc.)

**Comment by jramapuram** [comment]
Yup, the line is still there. Just using a stock build from `master`. Running centos7, but it shouldn't matter right? Since it's inside a container which as a predefined OS?

**Comment by felansu** [comment]
I have the same error, running windows 7. Any solution ?

**Comment by jramapuram** [comment]
Seems to be working with the latest build on git-rev 66d63d3da5b2 for zeppelin.
